/**
 * LucideIcon — Dynamic icon renderer using Lucide React
 * Pass iconName (string from content.ts) and it renders the correct icon.
 */
import {
  Scale,
  Handshake,
  MessageSquare,
  MessageCircle,
  Link2,
  FolderOpen,
  UserPlus,
  ShieldCheck,
  Award,
  Clock,
  Lock,
  Users,
  Zap,
  BadgeDollarSign,
  FileCheck,
  Globe,
  Lightbulb,
  TrendingUp,
  Building2,
  Heart,
  Shield,
  FileText,
  Video,
  UserCheck,
  Briefcase,
  Landmark,
  Home,
  ShoppingCart,
  RefreshCw,
  CheckCircle,
  CheckCircle2,
  ArrowRight,
  Star,
  Quote,
  ChevronDown,
  Mail,
  Phone,
  MapPin,
  Menu,
  X,
  Share2,
  PlayCircle,
  AtSign,
  Sparkles,
  Banknote,
  Headphones,
  Key,
  BookOpen,
  GitBranch,
  Package,
  Bug,
  Calendar,
  Code2,
  Library,
  GraduationCap,
  type LucideProps,
} from "lucide-react";

const iconMap: Record<string, React.ComponentType<LucideProps>> = {
  Scale,
  Handshake,
  MessageSquare,
  MessageCircle,
  Link2,
  FolderOpen,
  UserPlus,
  ShieldCheck,
  Award,
  Clock,
  Lock,
  Users,
  Zap,
  BadgeDollarSign,
  FileCheck,
  Globe,
  Lightbulb,
  TrendingUp,
  Building2,
  Heart,
  Shield,
  FileText,
  Video,
  UserCheck,
  Briefcase,
  Landmark,
  Home,
  ShoppingCart,
  RefreshCw,
  CheckCircle,
  CheckCircle2,
  ArrowRight,
  Star,
  Quote,
  ChevronDown,
  Mail,
  Phone,
  MapPin,
  Menu,
  X,
  Sparkles,
  Banknote,
  Headphones,
  Key,
  BookOpen,
  GitBranch,
  Package,
  Bug,
  Calendar,
  Code2,
  Library,
  GraduationCap,
  // Social icon aliases
  LinkedIn: Share2,
  Twitter: AtSign,
  YouTube: PlayCircle,
  Share2,
  AtSign,
  PlayCircle,
};

interface LucideIconProps extends LucideProps {
  name: string;
}

export function LucideIcon({ name, ...props }: LucideIconProps) {
  const Icon = iconMap[name];
  if (!Icon) {
    // Fallback: render a circle placeholder if icon not found
    return <span className="w-5 h-5 rounded-full bg-primary/30 inline-block" />;
  }
  return <Icon {...props} />;
}

export default LucideIcon;
